### ISSUE TITLE
GregorianCalendar.getTime not compatible with original Date.getTime

### ISSUE THREAD

**Issue by YDSS** [yiminghe/gregorian-calendar#6]
Hi! I got confused about `GregorianCalendar` Object convert to JS **original Date Object** with `getTime`. Assuming I got a GregorianCalendar Object which had a date, then got **unix timestamp** by using `GregorianCalendar.getTime`. If I create an original Date with this timestamp, **the day of month** will be one more than the correct one. Which is wrong of me?

**Comment by yiminghe** [comment]
you need to specify locale.

defaults to en-us

**Comment by YDSS** [comment]
@yiminghe I specify locale in `rc-calendar`, still not working

``` js
    import locale from 'rc-calendar/lib/locale/zh_CN';

    ...

    const calendar = (
            <Calendar
                showDateInput={false}
                locale={locale}
                onSelect={this.onChangeDate.bind(this)}
            />
        )
```

**Comment by yiminghe** [comment]
http://react-component.github.io/calendar/examples/antd-calendar.html

**Comment by YDSS** [comment]
my bad, it's working, thanks!
