### ISSUE TITLE
Are all methods listed in README implemented?

### ISSUE THREAD

**Issue by modomodo** [yiminghe/gregorian-calendar#9]
I'm trying to implement the functionality of `GregorianCalendar.addMonth(-1)` however, upon inspection in Webstorm, the method is not resolvable:

![image](https://cloud.githubusercontent.com/assets/5679726/15641626/f478dcd0-264a-11e6-89e1-de680a0e07b5.png)

Upon looking at the source code, its noticed there are some comments defining multiple methods but without any implementations:

![image](https://cloud.githubusercontent.com/assets/5679726/15641572/8ab930ec-264a-11e6-9665-47c728c04f1b.png)

This is using the latest version of the package: `4.1.3`

**Comment by yiminghe** [comment]
https://github.com/yiminghe/gregorian-calendar/blob/1d6e903f525ef60efc9683628f9dc582600330a0/src/gregorian-calendar.js#L1329
